version = 1

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "iRealisatie - Ministerie van Volksgezondheid, Welzijn en Sport"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "iRealisatie - Ministerie van Volksgezondheid, Welzijn en Sport"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "src/**/themes/rijkshuisstijl"
precedence = "aggregate"
SPDX-FileCopyrightText = "iRealisatie - Ministerie van Volksgezondheid, Welzijn en Sport"
SPDX-License-Identifier = "LicenseRef-Rijkshuisstijl"
